# Generated by Django 4.2.16 on 2024-11-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_propertylisting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylisting',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='property_images/'),
        ),
    ]
