# Generated by Django 4.2.16 on 2024-11-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_propertylisting_images_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
